[package]
name = "budokan_validators"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_interfaces.workspace = true
budokan_interfaces.workspace = true
budokan_entry_validator.workspace = true

[dev-dependencies]
snforge_std.workspace = true
budokan_test_common.workspace = true

[tool.snforge]
[[tool.snforge.fork]]
name = "sepolia"
url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_10"
block_id.number = "6326561"

[[tool.snforge.fork]]
name = "mainnet"
url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_10"
block_id.number = "6123632"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "budokan_test_common::mocks::entry_validator_mock::entry_validator_mock",
    "budokan_test_common::mocks::open_entry_validator_mock::open_entry_validator_mock",
]
