[workspace]
members = [
    "packages/interfaces",
    "packages/entry_requirement",
    "packages/entry_fee",
    "packages/prize",
    "packages/presets",
    "packages/test_common",
]

[workspace.package]
version = "0.1.3"
edition = "2024_07"

[workspace.dependencies]
starknet = "2.15.1"
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_merkle_tree = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
snforge_std = "0.56.0"
metagame_extensions_interfaces = { path = "packages/interfaces" }
metagame_extensions_entry_requirement = { path = "packages/entry_requirement" }
metagame_extensions_entry_fee = { path = "packages/entry_fee" }
metagame_extensions_prize = { path = "packages/prize" }
metagame_extensions_presets = { path = "packages/presets" }
metagame_extensions_test_common = { path = "packages/test_common" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.scripts]
test = "snforge test --workspace"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
