[workspace]
members = [
    "packages/interfaces",
    "packages/entry_requirement",
    "packages/entry_fee",
    "packages/prize",
    "packages/presets",
    "packages/test_common",
]

[workspace.package]
version = "0.1.0"
edition = "2024_07"

[workspace.dependencies]
starknet = "2.15.1"
openzeppelin_introspection = "3.0.0"
openzeppelin_interfaces = "2.1.0"
snforge_std = "0.56.0"
interfaces = { path = "packages/interfaces" }
entry_requirement_extension_component = { path = "packages/entry_requirement" }
entry_fee_extension_component = { path = "packages/entry_fee" }
prize_extension_component = { path = "packages/prize" }
entry_requirement_extensions = { path = "packages/presets" }
test_common = { path = "packages/test_common" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.scripts]
test = "snforge test --workspace"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
