[package]
name = "entry_validator_component"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
entry_validator_interfaces.workspace = true

[lib]
