[package]
name = "budokan_entry_validator"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
budokan_interfaces.workspace = true

[lib]
