[package]
name = "entry_requirement_extension_component"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
metagame_extension_interfaces.workspace = true

[lib]
