[package]
name = "metagame_extensions_test_common"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_interfaces.workspace = true
snforge_std.workspace = true
metagame_extensions_interfaces.workspace = true
metagame_extensions_entry_requirement.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
