[package]
name = "test_common"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_interfaces.workspace = true
snforge_std.workspace = true
metagame_extension_interfaces.workspace = true
entry_requirement_extension_component.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
