[package]
name = "metagame_extensions_prize"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection.workspace = true
metagame_extensions_interfaces.workspace = true

[lib]
